# Generated by Django 3.1 on 2020-08-04 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('publication_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('application_number', models.CharField(max_length=20)),
                ('country_code', models.CharField(max_length=5)),
                ('filing_date', models.DateField(null=True)),
                ('assignee', models.CharField(max_length=500, null=True)),
                ('title', models.CharField(max_length=500, null=True)),
                ('abstract', models.TextField(null=True)),
                ('claims', models.TextField(null=True)),
            ],
            options={
                'db_table': 'patents1000',
            },
        ),
    ]
